name: unit_tests

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm ci

      - name: TypeScript Check
        run: npm run lint

      - name: Jest Tests
        run: npm test
