name: unit_tests

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - run: npm ci

      - name: TypeScript Check
        run: npm run lint

      - name: Jest Tests
        run: npm test
